/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import {CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const DeploymentExtendedFilter = {
  required: false,
  serializedName: 'DeploymentExtendedFilter',
  type: {
    name: 'Composite',
    className: 'DeploymentExtendedFilter',
    modelProperties: {
      provisioningState: {
        required: false,
        serializedName: 'provisioningState',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const GenericResourceFilter = {
  required: false,
  serializedName: 'GenericResourceFilter',
  type: {
    name: 'Composite',
    className: 'GenericResourceFilter',
    modelProperties: {
      resourceType: {
        required: false,
        serializedName: 'resourceType',
        type: {
          name: 'String'
        }
      },
      tagname: {
        required: false,
        serializedName: 'tagname',
        type: {
          name: 'String'
        }
      },
      tagvalue: {
        required: false,
        serializedName: 'tagvalue',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourceGroupFilter = {
  required: false,
  serializedName: 'ResourceGroupFilter',
  type: {
    name: 'Composite',
    className: 'ResourceGroupFilter',
    modelProperties: {
      tagName: {
        required: false,
        serializedName: 'tagName',
        type: {
          name: 'String'
        }
      },
      tagValue: {
        required: false,
        serializedName: 'tagValue',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const TemplateLink = {
  required: false,
  serializedName: 'TemplateLink',
  type: {
    name: 'Composite',
    className: 'TemplateLink',
    modelProperties: {
      uri: {
        required: true,
        serializedName: 'uri',
        type: {
          name: 'String'
        }
      },
      contentVersion: {
        required: false,
        serializedName: 'contentVersion',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ParametersLink = {
  required: false,
  serializedName: 'ParametersLink',
  type: {
    name: 'Composite',
    className: 'ParametersLink',
    modelProperties: {
      uri: {
        required: true,
        serializedName: 'uri',
        type: {
          name: 'String'
        }
      },
      contentVersion: {
        required: false,
        serializedName: 'contentVersion',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const DebugSetting = {
  required: false,
  serializedName: 'DebugSetting',
  type: {
    name: 'Composite',
    className: 'DebugSetting',
    modelProperties: {
      detailLevel: {
        required: false,
        serializedName: 'detailLevel',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const DeploymentProperties = {
  required: false,
  serializedName: 'DeploymentProperties',
  type: {
    name: 'Composite',
    className: 'DeploymentProperties',
    modelProperties: {
      template: {
        required: false,
        serializedName: 'template',
        type: {
          name: 'Object'
        }
      },
      templateLink: {
        required: false,
        serializedName: 'templateLink',
        type: {
          name: 'Composite',
          className: 'TemplateLink'
        }
      },
      parameters: {
        required: false,
        serializedName: 'parameters',
        type: {
          name: 'Object'
        }
      },
      parametersLink: {
        required: false,
        serializedName: 'parametersLink',
        type: {
          name: 'Composite',
          className: 'ParametersLink'
        }
      },
      mode: {
        required: true,
        serializedName: 'mode',
        type: {
          name: 'Enum',
          allowedValues: [ 'Incremental', 'Complete' ]
        }
      },
      debugSetting: {
        required: false,
        serializedName: 'debugSetting',
        type: {
          name: 'Composite',
          className: 'DebugSetting'
        }
      }
    }
  }
};

export const Deployment = {
  required: false,
  serializedName: 'Deployment',
  type: {
    name: 'Composite',
    className: 'Deployment',
    modelProperties: {
      properties: {
        required: true,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'DeploymentProperties'
        }
      }
    }
  }
};

export const DeploymentExportResult = {
  required: false,
  serializedName: 'DeploymentExportResult',
  type: {
    name: 'Composite',
    className: 'DeploymentExportResult',
    modelProperties: {
      template: {
        required: false,
        serializedName: 'template',
        type: {
          name: 'Object'
        }
      }
    }
  }
};

export const ResourceManagementErrorWithDetails = {
  required: false,
  serializedName: 'ResourceManagementErrorWithDetails',
  type: {
    name: 'Composite',
    className: 'ResourceManagementErrorWithDetails',
    modelProperties: {
      code: {
        required: false,
        readOnly: true,
        serializedName: 'code',
        type: {
          name: 'String'
        }
      },
      message: {
        required: false,
        readOnly: true,
        serializedName: 'message',
        type: {
          name: 'String'
        }
      },
      target: {
        required: false,
        readOnly: true,
        serializedName: 'target',
        type: {
          name: 'String'
        }
      },
      details: {
        required: false,
        readOnly: true,
        serializedName: 'details',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'ResourceManagementErrorWithDetailsElementType',
              type: {
                name: 'Composite',
                className: 'ResourceManagementErrorWithDetails'
              }
          }
        }
      }
    }
  }
};

export const AliasPathType = {
  required: false,
  serializedName: 'AliasPathType',
  type: {
    name: 'Composite',
    className: 'AliasPathType',
    modelProperties: {
      path: {
        required: false,
        serializedName: 'path',
        type: {
          name: 'String'
        }
      },
      apiVersions: {
        required: false,
        serializedName: 'apiVersions',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      }
    }
  }
};

export const AliasType = {
  required: false,
  serializedName: 'AliasType',
  type: {
    name: 'Composite',
    className: 'AliasType',
    modelProperties: {
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      paths: {
        required: false,
        serializedName: 'paths',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'AliasPathTypeElementType',
              type: {
                name: 'Composite',
                className: 'AliasPathType'
              }
          }
        }
      }
    }
  }
};

export const ProviderResourceType = {
  required: false,
  serializedName: 'ProviderResourceType',
  type: {
    name: 'Composite',
    className: 'ProviderResourceType',
    modelProperties: {
      resourceType: {
        required: false,
        serializedName: 'resourceType',
        type: {
          name: 'String'
        }
      },
      locations: {
        required: false,
        serializedName: 'locations',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      aliases: {
        required: false,
        serializedName: 'aliases',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'AliasTypeElementType',
              type: {
                name: 'Composite',
                className: 'AliasType'
              }
          }
        }
      },
      apiVersions: {
        required: false,
        serializedName: 'apiVersions',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      }
    }
  }
};

export const Provider = {
  required: false,
  serializedName: 'Provider',
  type: {
    name: 'Composite',
    className: 'Provider',
    modelProperties: {
      id: {
        required: false,
        readOnly: true,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      namespace: {
        required: false,
        serializedName: 'namespace',
        type: {
          name: 'String'
        }
      },
      registrationState: {
        required: false,
        readOnly: true,
        serializedName: 'registrationState',
        type: {
          name: 'String'
        }
      },
      resourceTypes: {
        required: false,
        readOnly: true,
        serializedName: 'resourceTypes',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'ProviderResourceTypeElementType',
              type: {
                name: 'Composite',
                className: 'ProviderResourceType'
              }
          }
        }
      }
    }
  }
};

export const BasicDependency = {
  required: false,
  serializedName: 'BasicDependency',
  type: {
    name: 'Composite',
    className: 'BasicDependency',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      resourceType: {
        required: false,
        serializedName: 'resourceType',
        type: {
          name: 'String'
        }
      },
      resourceName: {
        required: false,
        serializedName: 'resourceName',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const Dependency = {
  required: false,
  serializedName: 'Dependency',
  type: {
    name: 'Composite',
    className: 'Dependency',
    modelProperties: {
      dependsOn: {
        required: false,
        serializedName: 'dependsOn',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'BasicDependencyElementType',
              type: {
                name: 'Composite',
                className: 'BasicDependency'
              }
          }
        }
      },
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      resourceType: {
        required: false,
        serializedName: 'resourceType',
        type: {
          name: 'String'
        }
      },
      resourceName: {
        required: false,
        serializedName: 'resourceName',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const DeploymentPropertiesExtended = {
  required: false,
  serializedName: 'DeploymentPropertiesExtended',
  type: {
    name: 'Composite',
    className: 'DeploymentPropertiesExtended',
    modelProperties: {
      provisioningState: {
        required: false,
        readOnly: true,
        serializedName: 'provisioningState',
        type: {
          name: 'String'
        }
      },
      correlationId: {
        required: false,
        readOnly: true,
        serializedName: 'correlationId',
        type: {
          name: 'String'
        }
      },
      timestamp: {
        required: false,
        readOnly: true,
        serializedName: 'timestamp',
        type: {
          name: 'DateTime'
        }
      },
      outputs: {
        required: false,
        serializedName: 'outputs',
        type: {
          name: 'Object'
        }
      },
      providers: {
        required: false,
        serializedName: 'providers',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'ProviderElementType',
              type: {
                name: 'Composite',
                className: 'Provider'
              }
          }
        }
      },
      dependencies: {
        required: false,
        serializedName: 'dependencies',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'DependencyElementType',
              type: {
                name: 'Composite',
                className: 'Dependency'
              }
          }
        }
      },
      template: {
        required: false,
        serializedName: 'template',
        type: {
          name: 'Object'
        }
      },
      templateLink: {
        required: false,
        serializedName: 'templateLink',
        type: {
          name: 'Composite',
          className: 'TemplateLink'
        }
      },
      parameters: {
        required: false,
        serializedName: 'parameters',
        type: {
          name: 'Object'
        }
      },
      parametersLink: {
        required: false,
        serializedName: 'parametersLink',
        type: {
          name: 'Composite',
          className: 'ParametersLink'
        }
      },
      mode: {
        required: false,
        serializedName: 'mode',
        type: {
          name: 'Enum',
          allowedValues: [ 'Incremental', 'Complete' ]
        }
      },
      debugSetting: {
        required: false,
        serializedName: 'debugSetting',
        type: {
          name: 'Composite',
          className: 'DebugSetting'
        }
      }
    }
  }
};

export const DeploymentValidateResult = {
  required: false,
  serializedName: 'DeploymentValidateResult',
  type: {
    name: 'Composite',
    className: 'DeploymentValidateResult',
    modelProperties: {
      error: {
        required: false,
        serializedName: 'error',
        type: {
          name: 'Composite',
          className: 'ResourceManagementErrorWithDetails'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'DeploymentPropertiesExtended'
        }
      }
    }
  }
};

export const DeploymentExtended = {
  required: false,
  serializedName: 'DeploymentExtended',
  type: {
    name: 'Composite',
    className: 'DeploymentExtended',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      name: {
        required: true,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'DeploymentPropertiesExtended'
        }
      }
    }
  }
};

export const Plan = {
  required: false,
  serializedName: 'Plan',
  type: {
    name: 'Composite',
    className: 'Plan',
    modelProperties: {
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      publisher: {
        required: false,
        serializedName: 'publisher',
        type: {
          name: 'String'
        }
      },
      product: {
        required: false,
        serializedName: 'product',
        type: {
          name: 'String'
        }
      },
      promotionCode: {
        required: false,
        serializedName: 'promotionCode',
        type: {
          name: 'String'
        }
      },
      version: {
        required: false,
        serializedName: 'version',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const Sku = {
  required: false,
  serializedName: 'Sku',
  type: {
    name: 'Composite',
    className: 'Sku',
    modelProperties: {
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      tier: {
        required: false,
        serializedName: 'tier',
        type: {
          name: 'String'
        }
      },
      size: {
        required: false,
        serializedName: 'size',
        type: {
          name: 'String'
        }
      },
      family: {
        required: false,
        serializedName: 'family',
        type: {
          name: 'String'
        }
      },
      model: {
        required: false,
        serializedName: 'model',
        type: {
          name: 'String'
        }
      },
      capacity: {
        required: false,
        serializedName: 'capacity',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const Identity = {
  required: false,
  serializedName: 'Identity',
  type: {
    name: 'Composite',
    className: 'Identity',
    modelProperties: {
      principalId: {
        required: false,
        readOnly: true,
        serializedName: 'principalId',
        type: {
          name: 'String'
        }
      },
      tenantId: {
        required: false,
        readOnly: true,
        serializedName: 'tenantId',
        type: {
          name: 'String'
        }
      },
      type: {
        required: false,
        serializedName: 'type',
        type: {
          name: 'Enum',
          allowedValues: [ 'SystemAssigned' ]
        }
      }
    }
  }
};

export const Resource = {
  required: false,
  serializedName: 'Resource',
  type: {
    name: 'Composite',
    className: 'Resource',
    modelProperties: {
      id: {
        required: false,
        readOnly: true,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      name: {
        required: false,
        readOnly: true,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      type: {
        required: false,
        readOnly: true,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      location: {
        required: false,
        serializedName: 'location',
        type: {
          name: 'String'
        }
      },
      tags: {
        required: false,
        serializedName: 'tags',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      }
    }
  }
};

export const GenericResource = {
  required: false,
  serializedName: 'GenericResource',
  type: {
    name: 'Composite',
    className: 'GenericResource',
    modelProperties: {
      id: {
        required: false,
        readOnly: true,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      name: {
        required: false,
        readOnly: true,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      type: {
        required: false,
        readOnly: true,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      location: {
        required: false,
        serializedName: 'location',
        type: {
          name: 'String'
        }
      },
      tags: {
        required: false,
        serializedName: 'tags',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      plan: {
        required: false,
        serializedName: 'plan',
        type: {
          name: 'Composite',
          className: 'Plan'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Object'
        }
      },
      kind: {
        required: false,
        serializedName: 'kind',
        constraints: {
          Pattern: '^[-\w\._,\(\)]+$'
        },
        type: {
          name: 'String'
        }
      },
      managedBy: {
        required: false,
        serializedName: 'managedBy',
        type: {
          name: 'String'
        }
      },
      sku: {
        required: false,
        serializedName: 'sku',
        type: {
          name: 'Composite',
          className: 'Sku'
        }
      },
      identity: {
        required: false,
        serializedName: 'identity',
        type: {
          name: 'Composite',
          className: 'Identity'
        }
      }
    }
  }
};

export const ResourceGroupProperties = {
  required: false,
  serializedName: 'ResourceGroupProperties',
  type: {
    name: 'Composite',
    className: 'ResourceGroupProperties',
    modelProperties: {
      provisioningState: {
        required: false,
        readOnly: true,
        serializedName: 'provisioningState',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourceGroup = {
  required: false,
  serializedName: 'ResourceGroup',
  type: {
    name: 'Composite',
    className: 'ResourceGroup',
    modelProperties: {
      id: {
        required: false,
        readOnly: true,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'ResourceGroupProperties'
        }
      },
      location: {
        required: true,
        serializedName: 'location',
        type: {
          name: 'String'
        }
      },
      managedBy: {
        required: false,
        serializedName: 'managedBy',
        type: {
          name: 'String'
        }
      },
      tags: {
        required: false,
        serializedName: 'tags',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      }
    }
  }
};

export const ResourceGroupPatchable = {
  required: false,
  serializedName: 'ResourceGroupPatchable',
  type: {
    name: 'Composite',
    className: 'ResourceGroupPatchable',
    modelProperties: {
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'ResourceGroupProperties'
        }
      },
      managedBy: {
        required: false,
        serializedName: 'managedBy',
        type: {
          name: 'String'
        }
      },
      tags: {
        required: false,
        serializedName: 'tags',
        type: {
          name: 'Dictionary',
          value: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      }
    }
  }
};

export const ResourcesMoveInfo = {
  required: false,
  serializedName: 'ResourcesMoveInfo',
  type: {
    name: 'Composite',
    className: 'ResourcesMoveInfo',
    modelProperties: {
      resources: {
        required: false,
        serializedName: 'resources',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      targetResourceGroup: {
        required: false,
        serializedName: 'targetResourceGroup',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ExportTemplateRequest = {
  required: false,
  serializedName: 'ExportTemplateRequest',
  type: {
    name: 'Composite',
    className: 'ExportTemplateRequest',
    modelProperties: {
      resources: {
        required: false,
        serializedName: 'resources',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'stringElementType',
              type: {
                name: 'String'
              }
          }
        }
      },
      options: {
        required: false,
        serializedName: 'options',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const TagCount = {
  required: false,
  serializedName: 'TagCount',
  type: {
    name: 'Composite',
    className: 'TagCount',
    modelProperties: {
      type: {
        required: false,
        serializedName: 'type',
        type: {
          name: 'String'
        }
      },
      value: {
        required: false,
        serializedName: 'value',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const TagValue = {
  required: false,
  serializedName: 'TagValue',
  type: {
    name: 'Composite',
    className: 'TagValue',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      tagValue: {
        required: false,
        serializedName: 'tagValue',
        type: {
          name: 'String'
        }
      },
      count: {
        required: false,
        serializedName: 'count',
        type: {
          name: 'Composite',
          className: 'TagCount'
        }
      }
    }
  }
};

export const TagDetails = {
  required: false,
  serializedName: 'TagDetails',
  type: {
    name: 'Composite',
    className: 'TagDetails',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      tagName: {
        required: false,
        serializedName: 'tagName',
        type: {
          name: 'String'
        }
      },
      count: {
        required: false,
        serializedName: 'count',
        type: {
          name: 'Composite',
          className: 'TagCount'
        }
      },
      values: {
        required: false,
        serializedName: 'values',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'TagValueElementType',
              type: {
                name: 'Composite',
                className: 'TagValue'
              }
          }
        }
      }
    }
  }
};

export const TargetResource = {
  required: false,
  serializedName: 'TargetResource',
  type: {
    name: 'Composite',
    className: 'TargetResource',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      resourceName: {
        required: false,
        serializedName: 'resourceName',
        type: {
          name: 'String'
        }
      },
      resourceType: {
        required: false,
        serializedName: 'resourceType',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const HttpMessage = {
  required: false,
  serializedName: 'HttpMessage',
  type: {
    name: 'Composite',
    className: 'HttpMessage',
    modelProperties: {
      content: {
        required: false,
        serializedName: 'content',
        type: {
          name: 'Object'
        }
      }
    }
  }
};

export const DeploymentOperationProperties = {
  required: false,
  serializedName: 'DeploymentOperationProperties',
  type: {
    name: 'Composite',
    className: 'DeploymentOperationProperties',
    modelProperties: {
      provisioningState: {
        required: false,
        readOnly: true,
        serializedName: 'provisioningState',
        type: {
          name: 'String'
        }
      },
      timestamp: {
        required: false,
        readOnly: true,
        serializedName: 'timestamp',
        type: {
          name: 'DateTime'
        }
      },
      serviceRequestId: {
        required: false,
        readOnly: true,
        serializedName: 'serviceRequestId',
        type: {
          name: 'String'
        }
      },
      statusCode: {
        required: false,
        readOnly: true,
        serializedName: 'statusCode',
        type: {
          name: 'String'
        }
      },
      statusMessage: {
        required: false,
        readOnly: true,
        serializedName: 'statusMessage',
        type: {
          name: 'Object'
        }
      },
      targetResource: {
        required: false,
        readOnly: true,
        serializedName: 'targetResource',
        type: {
          name: 'Composite',
          className: 'TargetResource'
        }
      },
      request: {
        required: false,
        readOnly: true,
        serializedName: 'request',
        type: {
          name: 'Composite',
          className: 'HttpMessage'
        }
      },
      response: {
        required: false,
        readOnly: true,
        serializedName: 'response',
        type: {
          name: 'Composite',
          className: 'HttpMessage'
        }
      }
    }
  }
};

export const DeploymentOperation = {
  required: false,
  serializedName: 'DeploymentOperation',
  type: {
    name: 'Composite',
    className: 'DeploymentOperation',
    modelProperties: {
      id: {
        required: false,
        readOnly: true,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      },
      operationId: {
        required: false,
        readOnly: true,
        serializedName: 'operationId',
        type: {
          name: 'String'
        }
      },
      properties: {
        required: false,
        serializedName: 'properties',
        type: {
          name: 'Composite',
          className: 'DeploymentOperationProperties'
        }
      }
    }
  }
};

export const ResourceProviderOperationDisplayProperties = {
  required: false,
  serializedName: 'ResourceProviderOperationDisplayProperties',
  type: {
    name: 'Composite',
    className: 'ResourceProviderOperationDisplayProperties',
    modelProperties: {
      publisher: {
        required: false,
        serializedName: 'publisher',
        type: {
          name: 'String'
        }
      },
      provider: {
        required: false,
        serializedName: 'provider',
        type: {
          name: 'String'
        }
      },
      resource: {
        required: false,
        serializedName: 'resource',
        type: {
          name: 'String'
        }
      },
      operation: {
        required: false,
        serializedName: 'operation',
        type: {
          name: 'String'
        }
      },
      description: {
        required: false,
        serializedName: 'description',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const SubResource = {
  required: false,
  serializedName: 'SubResource',
  type: {
    name: 'Composite',
    className: 'SubResource',
    modelProperties: {
      id: {
        required: false,
        serializedName: 'id',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourceGroupExportResult = {
  required: false,
  serializedName: 'ResourceGroupExportResult',
  type: {
    name: 'Composite',
    className: 'ResourceGroupExportResult',
    modelProperties: {
      template: {
        required: false,
        serializedName: 'template',
        type: {
          name: 'Object'
        }
      },
      error: {
        required: false,
        serializedName: 'error',
        type: {
          name: 'Composite',
          className: 'ResourceManagementErrorWithDetails'
        }
      }
    }
  }
};

export const DeploymentsListByResourceGroupOptionalParams = {
  required: false,
  serializedName: 'ListByResourceGroupOptions',
  type: {
    name: 'Composite',
    className: 'DeploymentsListByResourceGroupOptionalParams',
    modelProperties: {
      filter: {
        required: false,
        serializedName: '$filter',
        type: {
          name: 'String'
        }
      },
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const ProvidersListOptionalParams = {
  required: false,
  serializedName: 'ListOptions',
  type: {
    name: 'Composite',
    className: 'ProvidersListOptionalParams',
    modelProperties: {
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      },
      expand: {
        required: false,
        serializedName: '$expand',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ProvidersGetOptionalParams = {
  required: false,
  serializedName: 'GetOptions',
  type: {
    name: 'Composite',
    className: 'ProvidersGetOptionalParams',
    modelProperties: {
      expand: {
        required: false,
        serializedName: '$expand',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourcesListByResourceGroupOptionalParams = {
  required: false,
  serializedName: 'ListByResourceGroupOptions',
  type: {
    name: 'Composite',
    className: 'ResourcesListByResourceGroupOptionalParams',
    modelProperties: {
      filter: {
        required: false,
        serializedName: '$filter',
        type: {
          name: 'String'
        }
      },
      expand: {
        required: false,
        serializedName: '$expand',
        type: {
          name: 'String'
        }
      },
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const ResourcesListOptionalParams = {
  required: false,
  serializedName: 'ListOptions',
  type: {
    name: 'Composite',
    className: 'ResourcesListOptionalParams',
    modelProperties: {
      filter: {
        required: false,
        serializedName: '$filter',
        type: {
          name: 'String'
        }
      },
      expand: {
        required: false,
        serializedName: '$expand',
        type: {
          name: 'String'
        }
      },
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const ResourceGroupsListOptionalParams = {
  required: false,
  serializedName: 'ListOptions',
  type: {
    name: 'Composite',
    className: 'ResourceGroupsListOptionalParams',
    modelProperties: {
      filter: {
        required: false,
        serializedName: '$filter',
        type: {
          name: 'String'
        }
      },
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const DeploymentOperationsListOptionalParams = {
  required: false,
  serializedName: 'ListOptions',
  type: {
    name: 'Composite',
    className: 'DeploymentOperationsListOptionalParams',
    modelProperties: {
      top: {
        required: false,
        serializedName: '$top',
        type: {
          name: 'Number'
        }
      }
    }
  }
};

export const DeploymentListResult = {
  required: false,
  serializedName: 'DeploymentListResult',
  type: {
    name: 'Composite',
    className: 'DeploymentListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'DeploymentExtendedElementType',
              type: {
                name: 'Composite',
                className: 'DeploymentExtended'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ProviderListResult = {
  required: false,
  serializedName: 'ProviderListResult',
  type: {
    name: 'Composite',
    className: 'ProviderListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'ProviderElementType',
              type: {
                name: 'Composite',
                className: 'Provider'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourceListResult = {
  required: false,
  serializedName: 'ResourceListResult',
  type: {
    name: 'Composite',
    className: 'ResourceListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'GenericResourceElementType',
              type: {
                name: 'Composite',
                className: 'GenericResource'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const ResourceGroupListResult = {
  required: false,
  serializedName: 'ResourceGroupListResult',
  type: {
    name: 'Composite',
    className: 'ResourceGroupListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'ResourceGroupElementType',
              type: {
                name: 'Composite',
                className: 'ResourceGroup'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const TagsListResult = {
  required: false,
  serializedName: 'TagsListResult',
  type: {
    name: 'Composite',
    className: 'TagsListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'TagDetailsElementType',
              type: {
                name: 'Composite',
                className: 'TagDetails'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const DeploymentOperationsListResult = {
  required: false,
  serializedName: 'DeploymentOperationsListResult',
  type: {
    name: 'Composite',
    className: 'DeploymentOperationsListResult',
    modelProperties: {
      value: {
        required: false,
        serializedName: '',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'DeploymentOperationElementType',
              type: {
                name: 'Composite',
                className: 'DeploymentOperation'
              }
          }
        }
      },
      nextLink: {
        required: false,
        readOnly: true,
        serializedName: 'nextLink',
        type: {
          name: 'String'
        }
      }
    }
  }
};
